### ISSUE TITLE
Add root path to all API routes

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/token-metadata-service#99]
If hosting the TMS at a domain already used by another service, it would be useful if all TMS API routes began with the same root path to more easily identify traffic intended for the service.
Can a root path like `/metadata/v1/` be added to the beginning of all API routes this service provides?

**Comment by saralab** [comment]
@CharlieC3 @rafaelcr 
I love the idea of including versioning in the url , here's my preference: 

- we expect our developers to use and develop against the latest version and /metadata/nft should always be the latest version 
- If we choose to bind the url to a specific version, it should be so for a limited time only 

- For any latest version x for the API /metadata/nft  : 
/metadata/x/nft/ 
/metadata/x.y//nft/ 
Should be aliases. 

-Once there's a new version z and we no longer support vx : 
/metadata/x/nft/ 
Should return a 301 or 302 for redirection

**Comment by CharlieC3** [comment]
@saralab I think that sounds fine to me, though preferably the redirect logic would be contained and tracked with the service itself, rather than relying on the proxy layer to contain the logic. Otherwise we'd have to match deployed versions with updates to the proxy layer which can get quite messy and bespoke.
